#ifndef PROJECT_BASE_V1_1_THREADSTATE_HPP
#define PROJECT_BASE_V1_1_THREADSTATE_HPP

enum States {
    READY = 0,
    RUNNING = 1,
    BLOCKED = 2,
    SLEEPING = 3,
    FINISHED = 4
};

#endif //PROJECT_BASE_V1_1_THREADSTATE_HPP